// Emojis elegibles en el IconPicker. Se guardan crudos como `notebooks.icon` —
// NotebookIcon ya los dibuja como texto, y los notebooks importados de Notion vienen así.
// Curados a mano. El valor es el keyword del buscador (en español). No usamos
// Intl.DisplayNames: el type "emoji" depende del ICU del runtime y v8 de Node lo
// rechaza fuera de builds full-ICU.
export const EMOJI_KEYWORDS: Record<string, string> = {
  "😀": "caras sonrisa feliz",
  "😄": "sonrisa feliz",
  "😅": "risa sudor",
  "😂": "llorar risa gracioso lagrimas",
  "🙂": "sonrisa",
  "😉": "guiño",
  "😍": "amor ojos corazon",
  "🤩": "estrellas impresionado",
  "😎": "gafas sol",
  "🤔": "pensando duda",
  "🥳": "fiesta cumpleaños",
  "😴": "dormir sueño",
  "😭": "llorar triste",
  "🤯": "explotar mente",
  "🥰": "amor sonrisa corazones",
  "😌": "alivio tranquilo relajado",
  "🤗": "abrazo",
  "🤫": "silencio callar",
  "🫡": "saludo militar respeto",
  "🥱": "bostezo cansado",
  "😈": "diablo travieso",
  "🤖": "robot",
  "👻": "fantasma",
  "🤠": "vaquero",
  "🥸": "disfraz incognito",
  "🤪": "loco locura",
  "🤨": "ceja desconfianza",
  "🤤": "baba antojo",
  "😪": "somnoliento cansado",
  "😵": "mareado aturdido",
  "🥶": "frio congelado",
  "🥵": "calor acalorado",
  "😱": "grito miedo susto",
  "😡": "enojado furia",
  "🤬": "insultos enojado",
  "😳": "avergonzado ruborizado",
  "🥺": "ojitos suplica",
  "😬": "dientes incomodo",
  "🤐": "boca cerrada secreto",
  "🤢": "asco nauseas",
  "🤮": "vomitar asco",
  "🤧": "estornudo gripa",
  "😷": "mascarilla enfermo",
  "🤒": "termómetro enfermo",
  "🤕": "vendaje herido",
  "🤑": "dinero billetes",
  "🫠": "derretido calor",
  "🥴": "mareado borracho",
  "😋": "rico delicioso",
  "😜": "lengua guiño loco",
  "🤭": "risa tapada boca",
  "🫣": "espiando mirar",
  "🧐": "monoculo investigar",
  "👍": "pulgar bien",
  "👎": "pulgar mal",
  "👏": "aplauso",
  "🙌": "manos arriba celebrar",
  "💪": "musculo fuerte",
  "🙏": "gracias oración",
  "🤝": "acuerdo apretón",
  "🤙": "llamame",
  "🖖": "vulcano star trek",
  "🤟": "te quiero amor mano",
  "🤘": "rock cuernos",
  "👌": "perfecto ok",
  "✌️": "paz victoria",
  "🤞": "dedos cruzados suerte",
  "🫰": "dedos corazon dinero",
  "🫶": "manos corazon",
  "👋": "hola adiós saludo",
  "🤚": "mano alta",
  "🖐": "mano abierta cinco",
  "✋": "mano alto",
  "🫵": "señalar vos",
  "👉": "apuntar dedo",
  "👀": "ojos mirar",
  "🧠": "cerebro",
  "🫀": "corazon anatomia",
  "🦷": "diente dentistra",
  "🦴": "hueso",
  "🗣": "hablar voz",
  "👣": "huellas pasos",
  "🤱": "amamantar bebe",
  "❤️": "amor corazon rojo",
  "🧡": "naranja",
  "💛": "amarillo",
  "💚": "verde",
  "💙": "azul",
  "💜": "violeta",
  "🖤": "negro",
  "🤍": "blanco",
  "🤎": "marron",
  "💔": "corazon roto",
  "❤️‍🔥": "corazon fuego pasion",
  "❤️‍🩹": "corazon sanando",
  "💕": "corazones amor",
  "💞": "corazones giro amor",
  "💓": "latido corazon",
  "💗": "creciendo corazon",
  "💖": "brillante corazon",
  "💘": "flecha corazon amor",
  "💝": "regalo corazon",
  "☮️": "paz",
  "✝️": "cruz religion",
  "☯️": "yin yang equilibrio",
  "🔱": "tridente",
  "⚛️": "atomica ciencia simbolo",
  "⭐": "estrella favorito",
  "🌟": "estrella brillo",
  "✨": "destellos brillo magia",
  "⚡": "rayo energia",
  "🔥": "fuego llama",
  "💥": "explosion boom",
  "💫": "estrella giro mareo",
  "☄️": "cometa",
  "🎉": "celebracion fiesta",
  "🎊": "confeti fiesta",
  "🎁": "regalo",
  "🎈": "globo fiesta",
  "🎂": "torta cumpleaños",
  "🏆": "trofeo premio ganador",
  "🥇": "medalla oro primer puesto",
  "🥈": "medalla plata segundo",
  "🥉": "medalla bronce tercero",
  "🎯": "objetivo diana meta",
  "🚀": "cohete lanzamiento",
  "🪩": "bola disco fiesta",
  "🎇": "fuego artificial",
  "🧨": "dinamita",
  "👑": "corona rey",
  "🪄": "varita magia",
  "🔔": "campana",
  "📣": "megafono anunciar",
  "📢": "megafono gritar",
  "🪅": "piñata",
  "🎗": "cinta recuerdo",
  "🎖": "medalla militar",
  "🍎": "manzana",
  "🍊": "naranja fruta",
  "🍋": "limón",
  "🍌": "banana",
  "🍉": "sandia",
  "🍇": "uvas",
  "🍓": "frutilla",
  "🫐": "arandanos",
  "🍒": "cerezas",
  "🍑": "durazno",
  "🥭": "mango",
  "🍍": "anana pina",
  "🥝": "kiwi",
  "🥑": "palta aguacate",
  "🥕": "zanahoria",
  "🌽": "choclo maiz",
  "🍅": "tomate",
  "🥔": "papa patata",
  "🥦": "brócoli",
  "🥬": "lechuga verdura",
  "🧄": "ajo",
  "🧅": "cebolla",
  "🥜": "mani",
  "🍞": "pan",
  "🥐": "medialuna croissant",
  "🥖": "baguette",
  "🥨": "brezel",
  "🧇": "waffle",
  "🧀": "queso",
  "🍖": "carne hueso",
  "🍗": "pollo",
  "🥓": "panceta bacon",
  "🍔": "hamburguesa",
  "🍟": "papas fritas",
  "🍕": "pizza",
  "🌭": "pancho hot dog",
  "🥪": "sandwich",
  "🌮": "taco",
  "🌯": "burrito",
  "🥙": "kebab",
  "🧆": "falafel",
  "🍳": "huevo frito",
  "🥘": "paella",
  "🍲": "sopa guiso",
  "🫕": "fondue",
  "🥗": "ensalada",
  "🍿": "pochoclos palomitas",
  "🧈": "manteca mantequilla",
  "🧂": "sal",
  "🥫": "lata conserva",
  "🍱": "bento",
  "🍣": "sushi",
  "🍤": "camarones rabas",
  "🍚": "arroz",
  "🍜": "ramen fideos",
  "🍝": "pasta fideos",
  "🍛": "curry",
  "🥟": "empanada",
  "🥠": "galleta fortuna",
  "🍦": "helado",
  "🍩": "dona",
  "🍪": "galletita",
  "🍫": "chocolate",
  "🍬": "caramelo",
  "🍭": "chupetin",
  "🧁": "cupcake",
  "🍰": "torta pastel",
  "🍯": "miel",
  "☕": "cafe",
  "🧋": "bubble tea",
  "🍵": "té",
  "🥤": "gaseosa vaso",
  "🧃": "jugo",
  "🍺": "cerveza",
  "🍻": "cerveza brindis",
  "🥂": "champagne brindis",
  "🍷": "vino",
  "🥃": "whisky",
  "🍸": "trago coctel",
  "🧉": "mate",
  "🥛": "leche",
  "🍼": "mamadera bebe",
  "🐶": "perro",
  "🐱": "gato",
  "🐭": "ratón",
  "🐰": "conejo",
  "🦊": "zorro",
  "🐻": "oso",
  "🐼": "panda",
  "🐨": "koala",
  "🐯": "tigre",
  "🦁": "león",
  "🐮": "vaca",
  "🐷": "cerdo",
  "🐸": "rana",
  "🐵": "mono",
  "🙈": "mono tapa ojos",
  "🐔": "gallina",
  "🐧": "pinguino",
  "🦆": "pato",
  "🦉": "búho",
  "🦇": "murciélago",
  "🐺": "lobo",
  "🐗": "jabali",
  "🐴": "caballo",
  "🦄": "unicornio",
  "🐝": "abeja",
  "🪱": "lombriz",
  "🐛": "oruga",
  "🦋": "mariposa",
  "🐌": "caracol",
  "🐞": "mariquita",
  "🐜": "hormiga",
  "🦗": "grillo",
  "🕷": "araña",
  "🦂": "escorpion",
  "🐢": "tortuga",
  "🐍": "serpiente",
  "🦎": "lagartija",
  "🦖": "dinosaurio",
  "🦕": "dinosaurio",
  "🐙": "pulpo",
  "🦑": "calamar",
  "🦐": "langostino",
  "🦞": "langosta",
  "🦀": "cangrejo",
  "🐡": "pez globo",
  "🐠": "pez tropical",
  "🐟": "pez",
  "🐬": "delfin",
  "🐳": "ballena",
  "🦈": "tiburon",
  "🐊": "cocodrilo",
  "🐅": "tigre",
  "🦓": "cebra",
  "🦍": "gorila",
  "🐘": "elefante",
  "🦛": "hipopotamo",
  "🦏": "rinoceronte",
  "🐪": "camello",
  "🦒": "jirafa",
  "🦘": "canguro",
  "🐄": "vaca",
  "🐎": "caballo",
  "🐖": "cerdo",
  "🐑": "oveja",
  "🐐": "cabra",
  "🦙": "llama",
  "🦌": "ciervo",
  "🐕": "perro",
  "🐈": "gato",
  "🐈‍⬛": "gato negro",
  "🐓": "gallo",
  "🦃": "pavo",
  "🦚": "pavo real",
  "🦜": "loro",
  "🦢": "cisne",
  "🕊": "paloma paz",
  "🐇": "conejo",
  "🐿": "ardilla",
  "🦔": "erizo",
  "🐾": "huellas patas",
  "🌲": "pino",
  "🌳": "árbol",
  "🌴": "palmera",
  "🌵": "cactus",
  "🌱": "brote crecer",
  "🌿": "hierba",
  "☘️": "trebol",
  "🍀": "trebol suerte",
  "🍁": "hoja maple",
  "🍂": "hojas otoño",
  "🍃": "hoja viento",
  "🌾": "trigo",
  "🌷": "tulipan",
  "🌹": "rosa",
  "🌺": "flor hibisco",
  "🌸": "flor cerezo",
  "🌼": "flor margarita",
  "🌻": "girasol",
  "💐": "ramo flores",
  "🪷": "loto",
  "🪴": "maceta",
  "🍄": "hongo",
  "🌊": "ola mar",
  "❄️": "copo nieve",
  "⛄": "muñeco nieve",
  "⚽": "futbol",
  "🏀": "basquet",
  "⚾": "beisbol",
  "🎾": "tenis",
  "🏐": "voley",
  "🏈": "futbol americano",
  "🏉": "rugby",
  "🏓": "ping pong",
  "🏸": "badminton",
  "🥊": "boxeo guante",
  "🥋": "artes marciales",
  "⛳": "golf",
  "⛸": "patinaje",
  "🎿": "esqui",
  "🏂": "snowboard",
  "🏋": "gimnasio pesas",
  "🤸": "gimnasia acrobacia",
  "🤼": "lucha",
  "🤽": "waterpolo",
  "🤾": "handball",
  "🚴": "ciclismo bici",
  "🚵": "mountain bike",
  "🧗": "escalada",
  "🏄": "surf",
  "🏊": "natación nadar",
  "🤿": "buceo",
  "🚣": "remo",
  "🏇": "equitacion",
  "🎱": "billar",
  "🎳": "bowling",
  "🥌": "curling",
  "🎣": "pesca",
  "🪁": "barrilete cometa",
  "🛹": "skate",
  "🛼": "patines",
  "🩰": "ballet",
  "💃": "baile danza",
  "🕺": "baile danza hombre",
  "🚗": "auto carro coche",
  "🚙": "camioneta",
  "🚕": "taxi",
  "🚌": "colectivo bus",
  "🚎": "trolebus",
  "🏎": "carrera autos",
  "🚓": "policia",
  "🚑": "ambulancia",
  "🚒": "bomberos",
  "🚐": "van",
  "🚚": "camion",
  "🚜": "tractor",
  "🛻": "pickup",
  "🏍": "moto",
  "🛵": "scooter moto",
  "🚲": "bicicleta",
  "🛴": "monopatin",
  "✈️": "avion viajar",
  "🛫": "despegue avion",
  "🛬": "aterrizaje avion",
  "🚁": "helicoptero",
  "🚂": "tren locomotora",
  "🚆": "tren",
  "🚇": "subte metro",
  "🚢": "barco",
  "⛵": "velero",
  "🛶": "canoa",
  "🚤": "lancha",
  "🛸": "ovni",
  "🗺": "mapa",
  "🧭": "brújula",
  "🏝": "isla",
  "🏔": "montaña",
  "🌋": "volcan",
  "🏕": "camping",
  "⛺": "carpa",
  "🏖": "playa",
  "🎡": "vuela mundo",
  "🎢": "montaña rusa",
  "🎠": "carrusel",
  "🗼": "torre",
  "🗽": "estatua libertad",
  "🏰": "castillo",
  "🕌": "mezquita",
  "🛕": "templo",
  "🕍": "sinagoga",
  "⛪": "iglesia",
  "🏠": "casa hogar",
  "🏡": "casa jardin",
  "🏢": "oficina edificio",
  "🏥": "hospital",
  "🏫": "escuela",
  "🏦": "banco",
  "🏨": "hotel",
  "🏬": "tienda",
  "🏭": "fabrica",
  "⛲": "fuente",
  "🌙": "luna noche",
  "☀️": "sol",
  "⛅": "parcialmente nublado",
  "☁️": "nube",
  "🌧": "lluvia",
  "⛈": "tormenta",
  "🌩": "rayo tormenta",
  "🌨": "nevada",
  "🌫": "niebla",
  "🌪": "tornado",
  "🌈": "arcoiris",
  "🌡": "termómetro",
  "🌍": "mundo tierra planeta",
  "🌎": "mundo america",
  "🌏": "mundo asia",
  "🪐": "planeta saturno",
  "🌛": "luna creciente",
  "🌜": "luna menguante",
  "🌚": "luna nueva cara",
  "🌝": "luna llena cara",
  "💻": "computadora laptop",
  "🖥": "computadora escritorio",
  "⌨️": "teclado",
  "🖱": "mouse",
  "🖨": "impresora",
  "📱": "celular telefono",
  "☎️": "telefono fijo",
  "📞": "llamada telefono",
  "📠": "fax",
  "🔋": "bateria",
  "🔌": "enchufe",
  "💡": "idea bombilla",
  "🔦": "linterna",
  "🛠": "herramientas",
  "🔧": "llave inglesa",
  "🔨": "martillo",
  "🪛": "destornillador",
  "⚙️": "engranaje config",
  "🧲": "imán",
  "🔫": "arma pistola",
  "💊": "pastilla medicina",
  "🩺": "estetoscopio doctor",
  "🩹": "curita",
  "🩻": "rayos x",
  "🔬": "microscopio",
  "🔭": "telescopio",
  "📡": "antena satelite",
  "🛰": "satelite",
  "🎧": "musica audifonos",
  "🎙": "microfono",
  "📻": "radio",
  "🎵": "nota musica",
  "🎶": "notas musica",
  "🎼": "partitura",
  "🎹": "piano",
  "🥁": "bateria musica",
  "🎸": "guitarra",
  "🎺": "trompeta",
  "🎻": "violin",
  "🎷": "saxo",
  "🎮": "videojuego joystick",
  "🕹": "joystick arcade",
  "🎲": "dado azar",
  "🧩": "puzzle rompecabezas",
  "♟": "ajedrez",
  "🃏": "joker cartas",
  "🎴": "cartas japonesas",
  "🎰": "casino",
  "🖼": "cuadro imagen",
  "🎨": "paleta arte",
  "🧵": "hilo costura",
  "🪡": "aguja costura",
  "🧶": "lana tejido",
  "👗": "vestido",
  "👟": "zapatillas",
  "🎩": "sombrero copa",
  "🧢": "gorra",
  "🎒": "mochila",
  "👝": "bolsita",
  "👜": "cartera bolso",
  "💼": "maletin trabajo",
  "👓": "anteojos lentes",
  "🕶": "anteojos sol",
  "💍": "anillo",
  "📚": "libros leer",
  "📖": "libro abierto",
  "📗": "libro verde",
  "📘": "libro azul",
  "📙": "libro naranja",
  "📕": "libro rojo",
  "🔖": "marcador",
  "📰": "periodico noticias",
  "📄": "documento",
  "📃": "documento",
  "📑": "paginas",
  "📊": "grafico barras",
  "📈": "grafico subiendo",
  "📉": "grafico bajando",
  "🗒": "notas",
  "📆": "calendario",
  "📅": "calendario fecha",
  "🗓": "calendario",
  "📇": "index",
  "📋": "portapapeles",
  "📌": "chincheta pin",
  "📍": "pin ubicacion",
  "📎": "clip",
  "📏": "regla",
  "📐": "escuadra",
  "✂️": "tijera",
  "🗄": "archivo",
  "🗑": "basura",
  "🔒": "candado cerrado",
  "🔓": "candado abierto",
  "🔑": "llave",
  "🗝": "llave antigua",
  "🪑": "silla",
  "🛏": "cama",
  "🚪": "puerta",
  "🪟": "ventana",
  "🛋": "sofa",
  "🛁": "bañera",
  "🚿": "ducha",
  "🧼": "jabon",
  "🧽": "esponja",
  "🧹": "escoba",
  "🪣": "balde",
  "🧺": "canasta",
  "🕰": "reloj antiguo",
  "⏰": "alarma",
  "⏳": "reloj arena",
  "⌛": "reloj arena",
  "💰": "dinero plata",
  "💎": "diamante gema",
  "⚖️": "balanza justicia",
  "🔗": "enlace link",
  "⛓": "cadenas",
  "🧳": "valija viaje",
  "✉️": "sobre carta",
  "📩": "mensaje",
  "📨": "mensaje",
  "📧": "email",
  "📮": "buzon",
  "📦": "paquete caja",
  "📤": "enviar",
  "📥": "recibir",
  "🗂": "carpetas",
  "📁": "carpeta",
  "📂": "carpeta abierta",
  "💳": "tarjeta credito",
  "💵": "billetes dolar",
  "💶": "euros",
  "💷": "libras",
  "🪙": "moneda",
  "💸": "dinero volando",
  "🧾": "factura recibo",
  "🛒": "carrito compras",
  "🥒": "pepino",
  "🍆": "berenjena",
  "🫑": "morrón pimiento",
  "🥯": "bagel",
  "🍙": "bola arroz",
  "🍢": "brochette",
  "🍡": "dango",
  "🍥": "kamaboko pescado",
  "🦪": "ostra perla",
  "🧊": "hielo hielo",
  "🐉": "dragón",
  "🐲": "cabeza dragón",
  "🦭": "foca",
  "🪸": "coral",
  "🐚": "caracola",
  "🪵": "madera leño",
  "🪨": "piedra roca",
  "♻️": "reciclar",
  "✅": "ok listo marca",
  "❌": "mal cruz",
  "⭕": "círculo",
  "❓": "interrogación duda",
  "❗": "exclamación atento",
  "💤": "sueño zzz",
  "💬": "diálogo hablar",
  "💭": "pensamiento burbuja",
  "💯": "cien puntos perfecto",
  "🔰": "principiante Japón",
  "⚜️": "lis flor de lis",
  "🪗": "acordeón",
  "🪕": "banjo",
  "🧸": "osito peluche",
  "🕯️": "vela",
  "🏹": "arco flecha tiro",
  "🪢": "nudo",
  "🧿": "ojo turco amuleto",
  "🪬": "hamsa amuleto",
  "🍐": "pera",
}

export const EMOJIS = Object.keys(EMOJI_KEYWORDS)

// Tonos de piel (IconPicker): el botón de color los cicla y se aplican al emoji actual si lo
// soporta. Sin soporte de ICU ni nada raro — son modificadores de zona selector-16 crudos.
export const TONES = ["🏻", "🏼", "🏽", "🏾", "🏿"]
// Emojis de la lista que aceptan tono (los de personas/manos).
export const TONEABLE = new Set([
  "👍",
  "👎",
  "👏",
  "🙌",
  "💪",
  "🙏",
  "🤙",
  "🖖",
  "🤟",
  "🤘",
  "👌",
  "✌️",
  "🤞",
  "🫰",
  "🫶",
  "👋",
  "🤚",
  "🖐",
  "✋",
  "🫵",
  "👉",
  "🏊",
  "🚴",
  "🚵",
  "🧗",
  "🏄",
  "🤿",
  "🚣",
  "🏇",
  "🤸",
  "🤼",
  "🤽",
  "🤾",
  "🏋",
  "💃",
  "🕺",
])

// Agrupados por lo que son. El buscador filtra dentro de cada grupo y los grupos vacíos
// no se muestran. `icon` es el ícono lucide del nav de categorías.
export const EMOJI_GROUPS: { label: string; icon: string; emojis: string[] }[] = [
  {
    icon: "Smile",
    label: "Caras",
    emojis: [
      "😀",
      "😄",
      "😅",
      "😂",
      "🙂",
      "😉",
      "😍",
      "🤩",
      "😎",
      "🤔",
      "🥳",
      "😴",
      "😭",
      "🤯",
      "🥰",
      "😌",
      "🤗",
      "🤫",
      "🫡",
      "🥱",
      "😈",
      "🤖",
      "👻",
      "🤠",
      "🥸",
      "🤪",
      "🤨",
      "🤤",
      "😪",
      "😵",
      "🥶",
      "🥵",
      "😱",
      "😡",
      "🤬",
      "😳",
      "🥺",
      "😬",
      "🤐",
      "🤢",
      "🤮",
      "🤧",
      "😷",
      "🤒",
      "🤕",
      "🤑",
      "🫠",
      "🥴",
      "😋",
      "😜",
      "🤭",
      "🫣",
      "🧐",
    ],
  },
  {
    icon: "Hand",
    label: "Gestos",
    emojis: [
      "👍",
      "👎",
      "👏",
      "🙌",
      "💪",
      "🙏",
      "🤝",
      "🤙",
      "🖖",
      "🤟",
      "🤘",
      "👌",
      "✌️",
      "🤞",
      "🫰",
      "🫶",
      "👋",
      "🤚",
      "🖐",
      "✋",
      "🫵",
      "👉",
      "👀",
      "🧠",
      "🫀",
      "🦷",
      "🦴",
      "🗣",
      "👣",
      "🤱",
    ],
  },
  {
    icon: "Heart",
    label: "Corazones",
    emojis: [
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "💔",
      "❤️‍🔥",
      "❤️‍🩹",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💘",
      "💝",
      "☮️",
      "✝️",
      "☯️",
      "🔱",
      "⚛️",
    ],
  },
  {
    icon: "PartyPopper",
    label: "Celebración",
    emojis: [
      "⭐",
      "🌟",
      "✨",
      "⚡",
      "🔥",
      "💥",
      "💫",
      "☄️",
      "🎉",
      "🎊",
      "🎁",
      "🎈",
      "🎂",
      "🏆",
      "🥇",
      "🥈",
      "🥉",
      "🎯",
      "🚀",
      "🪩",
      "🎇",
      "🧨",
      "👑",
      "🪄",
      "🔔",
      "📣",
      "📢",
      "🪅",
      "🎗",
      "🎖",
      "🔰",
      "⚜️",
    ],
  },
  {
    icon: "Pizza",
    label: "Comida",
    emojis: [
      "🍎",
      "🍊",
      "🍋",
      "🍌",
      "🍉",
      "🍇",
      "🍓",
      "🫐",
      "🍒",
      "🍑",
      "🥭",
      "🍍",
      "🥝",
      "🥑",
      "🥕",
      "🌽",
      "🍅",
      "🥔",
      "🥦",
      "🥬",
      "🧄",
      "🧅",
      "🥜",
      "🍞",
      "🥐",
      "🥖",
      "🥨",
      "🧇",
      "🧀",
      "🍖",
      "🍗",
      "🥓",
      "🍔",
      "🍟",
      "🍕",
      "🌭",
      "🥪",
      "🌮",
      "🌯",
      "🥙",
      "🧆",
      "🍳",
      "🥘",
      "🍲",
      "🫕",
      "🥗",
      "🍿",
      "🧈",
      "🧂",
      "🥫",
      "🍱",
      "🍣",
      "🍤",
      "🍚",
      "🍜",
      "🍝",
      "🍛",
      "🥟",
      "🥠",
      "🍦",
      "🍩",
      "🍪",
      "🍫",
      "🍬",
      "🍭",
      "🧁",
      "🍰",
      "🍯",
      "☕",
      "🧋",
      "🍵",
      "🥤",
      "🧃",
      "🍺",
      "🍻",
      "🥂",
      "🍷",
      "🥃",
      "🍸",
      "🧉",
      "🥛",
      "🍼",
      "🍐",
      "🥒",
      "🍆",
      "🫑",
      "🥯",
      "🍙",
      "🍢",
      "🍡",
      "🍥",
      "🦪",
      "🧊",
    ],
  },
  {
    icon: "PawPrint",
    label: "Animales y naturaleza",
    emojis: [
      "🐶",
      "🐱",
      "🐭",
      "🐰",
      "🦊",
      "🐻",
      "🐼",
      "🐨",
      "🐯",
      "🦁",
      "🐮",
      "🐷",
      "🐸",
      "🐵",
      "🙈",
      "🐔",
      "🐧",
      "🦆",
      "🦉",
      "🦇",
      "🐺",
      "🐗",
      "🐴",
      "🦄",
      "🐝",
      "🪱",
      "🐛",
      "🦋",
      "🐌",
      "🐞",
      "🐜",
      "🦗",
      "🕷",
      "🦂",
      "🐢",
      "🐍",
      "🦎",
      "🦖",
      "🦕",
      "🐙",
      "🦑",
      "🦐",
      "🦞",
      "🦀",
      "🐡",
      "🐠",
      "🐟",
      "🐬",
      "🐳",
      "🦈",
      "🐊",
      "🐅",
      "🦓",
      "🦍",
      "🐘",
      "🦛",
      "🦏",
      "🐪",
      "🦒",
      "🦘",
      "🐄",
      "🐎",
      "🐖",
      "🐑",
      "🐐",
      "🦙",
      "🦌",
      "🐕",
      "🐈",
      "🐈‍⬛",
      "🐓",
      "🦃",
      "🦚",
      "🦜",
      "🦢",
      "🕊",
      "🐇",
      "🐿",
      "🦔",
      "🐾",
      "🌲",
      "🌳",
      "🌴",
      "🌵",
      "🌱",
      "🌿",
      "☘️",
      "🍀",
      "🍁",
      "🍂",
      "🍃",
      "🌾",
      "🌷",
      "🌹",
      "🌺",
      "🌸",
      "🌼",
      "🌻",
      "💐",
      "🪷",
      "🪴",
      "🍄",
      "🌊",
      "❄️",
      "⛄",
      "🐉",
      "🐲",
      "🦭",
      "🪸",
      "🐚",
      "🪵",
      "🪨",
    ],
  },
  {
    icon: "Trophy",
    label: "Deportes",
    emojis: [
      "⚽",
      "🏀",
      "⚾",
      "🎾",
      "🏐",
      "🏈",
      "🏉",
      "🏓",
      "🏸",
      "🥊",
      "🥋",
      "⛳",
      "⛸",
      "🎿",
      "🏂",
      "🏋",
      "🤸",
      "🤼",
      "🤽",
      "🤾",
      "🚴",
      "🚵",
      "🧗",
      "🏄",
      "🏊",
      "🤿",
      "🚣",
      "🏇",
      "🎱",
      "🎳",
      "🥌",
      "🎣",
      "🪁",
      "🛹",
      "🛼",
      "🩰",
      "💃",
      "🕺",
    ],
  },
  {
    icon: "Plane",
    label: "Viajes y clima",
    emojis: [
      "🚗",
      "🚙",
      "🚕",
      "🚌",
      "🚎",
      "🏎",
      "🚓",
      "🚑",
      "🚒",
      "🚐",
      "🚚",
      "🚜",
      "🛻",
      "🏍",
      "🛵",
      "🚲",
      "🛴",
      "✈️",
      "🛫",
      "🛬",
      "🚁",
      "🚂",
      "🚆",
      "🚇",
      "🚢",
      "⛵",
      "🛶",
      "🚤",
      "🛸",
      "🗺",
      "🧭",
      "🏝",
      "🏔",
      "🌋",
      "🏕",
      "⛺",
      "🏖",
      "🎡",
      "🎢",
      "🎠",
      "🗼",
      "🗽",
      "🏰",
      "🕌",
      "🛕",
      "🕍",
      "⛪",
      "🏠",
      "🏡",
      "🏢",
      "🏥",
      "🏫",
      "🏦",
      "🏨",
      "🏬",
      "🏭",
      "⛲",
      "🌙",
      "☀️",
      "⛅",
      "☁️",
      "🌧",
      "⛈",
      "🌩",
      "🌨",
      "🌫",
      "🌪",
      "🌈",
      "🌡",
      "🌍",
      "🌎",
      "🌏",
      "🪐",
      "🌛",
      "🌜",
      "🌚",
      "🌝",
    ],
  },
  {
    icon: "Laptop",
    label: "Objetos",
    emojis: [
      "💻",
      "🖥",
      "⌨️",
      "🖱",
      "🖨",
      "📱",
      "☎️",
      "📞",
      "📠",
      "🔋",
      "🔌",
      "💡",
      "🔦",
      "🛠",
      "🔧",
      "🔨",
      "🪛",
      "⚙️",
      "🧲",
      "🔫",
      "💊",
      "🩺",
      "🩹",
      "🩻",
      "🔬",
      "🔭",
      "📡",
      "🛰",
      "🎧",
      "🎙",
      "📻",
      "🎵",
      "🎶",
      "🎼",
      "🎹",
      "🥁",
      "🎸",
      "🎺",
      "🎻",
      "🎷",
      "🎮",
      "🕹",
      "🎲",
      "🧩",
      "♟",
      "🃏",
      "🎴",
      "🎰",
      "🖼",
      "🎨",
      "🧵",
      "🪡",
      "🧶",
      "👗",
      "👟",
      "🎩",
      "🧢",
      "🎒",
      "👝",
      "👜",
      "💼",
      "👓",
      "🕶",
      "💍",
      "📚",
      "📖",
      "📗",
      "📘",
      "📙",
      "📕",
      "🔖",
      "📰",
      "📄",
      "📃",
      "📑",
      "📊",
      "📈",
      "📉",
      "🗒",
      "📆",
      "📅",
      "🗓",
      "📇",
      "📋",
      "📌",
      "📍",
      "📎",
      "📏",
      "📐",
      "✂️",
      "🗄",
      "🗑",
      "🔒",
      "🔓",
      "🔑",
      "🗝",
      "🪑",
      "🛏",
      "🚪",
      "🪟",
      "🛋",
      "🛁",
      "🚿",
      "🧼",
      "🧽",
      "🧹",
      "🪣",
      "🧺",
      "🕰",
      "⏰",
      "⏳",
      "⌛",
      "💰",
      "💎",
      "⚖️",
      "🔗",
      "⛓",
      "🧳",
      "✉️",
      "📩",
      "📨",
      "📧",
      "📮",
      "📦",
      "📤",
      "📥",
      "🗂",
      "📁",
      "📂",
      "💳",
      "💵",
      "💶",
      "💷",
      "🪙",
      "💸",
      "🧾",
      "🛒",
      "♻️",
      "✅",
      "❌",
      "⭕",
      "❓",
      "❗",
      "💤",
      "💬",
      "💭",
      "💯",
      "🪗",
      "🪕",
      "🧸",
      "🕯️",
      "🏹",
      "🪢",
      "🧿",
      "🪬",
    ],
  },
]
